### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by fengyuha** [He-Xiang-best/Facial-Expression-Recognition#3]
作者您好，我在训练vgg模型是为啥为出现FileNotFoundError: Couldn't find any class folder in face_images/vgg_verify_set.的错误
求解答，怎么设置才正确呢

Traceback (most recent call last):
  File "F:\deeplearning\facial-expression-recognition\model_ResNet.py", line 32, in <module>
    data_vaild = torchvision.datasets.ImageFolder(root=path_vaild,transform=transforms_vaild)
  File "F:\anaconda\envs\DL\lib\site-packages\torchvision\datasets\folder.py", line 310, in __init__
    super().__init__(
  File "F:\anaconda\envs\DL\lib\site-packages\torchvision\datasets\folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "F:\anaconda\envs\DL\lib\site-packages\torchvision\datasets\folder.py", line 219, in find_classes
    return find_classes(directory)
  File "F:\anaconda\envs\DL\lib\site-packages\torchvision\datasets\folder.py", line 43, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in face_images/vgg_verify_set.

Process finished with exit code 1

**Comment by hexiang10** [comment]
除了路径修改好以外，也要确保模型文件也要配置好哦
